apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: pipeline
spec:
  serviceAccountName: pipeline

  triggers:
    - bindings:
      - ref: cd-binding
      template:
        ref: cd-template